### ISSUE TITLE
新版本运行报错

### ISSUE THREAD

**Issue by ShmilyChen** [bilive/bilive_client#159]
UnhandledPromiseRejectionWarning: ReferenceError: appStatus is not defined
```
Apr 15 2020 20:15:16 : user Cookie已失效
(node:62944) UnhandledPromiseRejectionWarning: ReferenceError: appStatus is not defined
    at Online.refresh (C:\Nodejs\bilive_client_lz\build\bilive\lib\tv_client.js:102:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Online._cookieError (C:\Nodejs\bilive_client_lz\build\bilive\online.js:107:25)
    at async Online.getOnlineInfo (C:\Nodejs\bilive_client_lz\build\bilive\online.js:69:20)
    at async Online.Start (C:\Nodejs\bilive_client_lz\build\bilive\online.js:45:22)
    at async WebAPI._onCMD (C:\Nodejs\bilive_client_lz\build\bilive\webapi.js:182:48)
(node:62944) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:62944) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lzghzr** [comment]
临时启用的tv版接口, 还有一些问题

**Comment by ShmilyChen** [comment]
`appStatus is not defined`在class上面复制一遍app的枚举类就活了，hhhh

**Comment by LoidVC** [comment]
> 临时启用的tv版接口, 还有一些问题

歪，0418还是有问题emmm
